//
// Created by zouguibao on 2020-04-22.
//

#ifndef FFMPEGPROJECT_VIDEOPLAYERSTATUS_H
#define FFMPEGPROJECT_VIDEOPLAYERSTATUS_H

#endif //FFMPEGPROJECT_VIDEOPLAYERSTATUS_H
#define WL_THREAD_MAIN 1
#define WL_THREAD_CHILD 2

#define WL_FFMPEG_CAN_NOT_OPEN_URL 3
#define WL_FFMPEG_CAN_NOT_FIND_STREAMS 4
//#define WL_FFMPEG_CAN_NOT_OPEN_URL 5
#define LOG_SHOW true;